# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'FlatMessenger' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sirius
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'
  pod 'Firebase/Firestore', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'
  pod 'Firebase/Database', '~> 5.3.0'
  pod 'Firebase/Storage', '~> 5.3.0'

  target 'FlatMessenger-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'FlatMessengerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
